### ISSUE TITLE
Panics randomly in runtime

### ISSUE THREAD

**Issue by TriAnMan** [MauriceGit/skiplist#6]
Can't provide example right now. Maybe later.
Everything works fine with [sean-public/fast-skiplist](https://github.com/sean-public/fast-skiplist)

**Comment by MauriceGit** [comment]
Hi,
this doesn't really help me fix the issue ;)
I had the library running as key part of other projects of mine without it ever crashing or causing a panic. So if this might be an issue, I would very much like to fix it. 

If possible pleas provide some example or input where a panic happens.

**Comment by TriAnMan** [comment]
Sorry, can't provide an input because I can't collect it nor can't provide a core dump in case of NDA
I can only provide you a panic message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4f25b4]

goroutine 485 [running]:
github.com/MauriceGit/skiplist.(*SkipList).Insert(0xc004411340, 0x9b4a40, 0xc008cdc330)
	C:/Users/User/go/pkg/mod/github.com/!maurice!git/skiplist@v0.0.0-20181208093031-38aa714e3f14/skiplist.go:353 +0x474
```

**Comment by MauriceGit** [comment]
No problem, I understand.

I figured out the problem (see last commit message if interested) and wrote a fix. The tests work and I'll test internally. 
For now I close the issue, but please give it a try and report back if it works.

Thanks for the report :)

**Comment by TriAnMan** [comment]
Looks like now it's working. But I prefer to stay on [sean-public/fast-skiplist](https://github.com/sean-public/fast-skiplist).
